server:
  port: 8080
  servlet:
    context-path: /profile
spring:
  application:
    name: profile-service
  data:
    mongodb:
      uri: mongodb+srv://anh:27092004@backenddb.2qdkr.mongodb.net/?retryWrites=true&w=majority&appName=BackendDB
      database: KeyCloak
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/movie-web

idp:
  url: http://localhost:8180
  client-id: Movie_web
  client-secret: J0x148IBCmFNDn94eiomwyNgbNCzBuuS
